version: '1'
services:
  # postgres:
  #   image: postgres:14-alpine
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ~/apps/postgres:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=FoodOrdering

  redis:
    image: redis:7.0.6
    container_name: my_redis
    ports:
      - 6379:6379

  migration:
    build:
      context: .
    volumes:
      - .:/django
    command: python manage.py migrate --noinput
    # depends_on:
    #   - postgres

  app:
    build: .
    volumes:
      - .:/django
    environment:
      - DEBUG=True
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/FoodOrdering
      - SECRET_KEY=313e8357c0dd828e35bed2240d21bdaafe71f080a9370401358d1787349766a6
      - ALLOWED_HOSTS=127.0.0.1,*
      - CSRF_TRUSTED_ORIGINS=http://*
      - CORS_ALLOWED_ORIGINS=http://*
      - DEBUG=1
      - GENERATE_CODE=0
      - ENVIRONMENT=production
      # - LIVE=1
    ports:
      - 8000:8000
    image: app:django
    container_name: my_django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      # - postgres
      - migration
      - redis

  celery:
    restart: always
    build:
      context: .
    environment:
      - DEBUG=True
    volumes:
      - .:/django
    container_name: celery
    command: celery -A FoodOrdering worker -l info -B
    depends_on:
      - redis
      - app
